FROM node:20-alpine
RUN npm install -g pnpm@9.12.0
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter api exec prisma generate
CMD sh -c "pnpm --filter api exec prisma migrate deploy && pnpm --filter api start"
